version: "3"
services:
  nginx:
    ports:
      - "81:81" 
  node-app:
    build:
      context: . 
      args:
        NODE_ENV: development
    environment: 
      - NODE_ENV=production
    command: node index.js